apiVersion: v1
kind: Service
metadata:
  name: front-envoy-service
spec:
  type: LoadBalancer
  ports:
  - name: proxy
    port: 3000
    protocol: TCP
    targetPort: 10000
  - name: admin
    port: 3001
    protocol: TCP
    targetPort: 10001
  selector:
    app: front-envoy
