apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-envoy
spec:
  selector:
    matchLabels:
      app: front-envoy
  replicas: 1
  template:
    metadata:
      labels:
        app: front-envoy
    spec:
      volumes:
        - name: envoy
          configMap:
            name: envoy-config
      containers:
        - name: envoy
          image: envoyproxy/envoy:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: envoy
              mountPath: /etc/envoy
          command:
            - "/usr/local/bin/envoy"
          args:
            - "--config-path /etc/envoy/front-envoy.yaml"
            - "--service-cluster front-proxy"
          ports:
            - containerPort: 10000
              name: proxy
            - containerPort: 10001
              name: admin
