apiVersion: v1
kind: Service
metadata:
  name: front-envoy-service
spec:
  type: LoadBalancer
  ports:
  - name: front-envoy-port
    port: 5000
    targetPort: 80
    protocol: TCP
  selector:
    app: front-envoy
