apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-ruby
spec:
  selector:
    matchLabels:
      app: grpc-ruby
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-ruby
    spec:
      volumes:
        - name: envoy
          configMap:
            name: envoy-config
      containers:
        - name: grpc-ruby
          image: 'eks/grpc-ruby'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
        - name: envoy
          image: envoyproxy/envoy:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: envoy
              mountPath: /etc/envoy
          command:
            - "/usr/local/bin/envoy"
          args:
            - "--config-path /etc/envoy/service-envoy.yaml"
          ports:
            - containerPort: 10000
              name: envoy-sidecar
            - containerPort: 10001
              name: envoy-admin
