apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby
spec:
  selector:
    matchLabels:
      app: ruby
  replicas: 1
  template:
    metadata:
      labels:
        app: ruby
    spec:
      volumes:
        - name: envoy
          configMap:
            name: envoy-config
      containers:
        - name: ruby
          image: 'eks/ruby'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
        - name: envoy
          image: envoyproxy/envoy:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: envoy
              mountPath: /etc/envoy
          command:
            - "/usr/local/bin/envoy"
          args:
            - "--config-path /etc/envoy/sidecar-ruby.yaml"
          ports:
            - containerPort: 10000
              name: envoy-sidecar
            - containerPort: 10001
              name: envoy-admin
