version: '3'
services:
  go:
    build: go
    ports:
      - "8080:8080"
    volumes:
      - ./go:/go/src/app
  # ruby:
  #   build: ruby
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - ./ruby:/app
  # ruby_grpc:
  #   build: ruby_grpc
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./ruby_grpc:/app
